CREATE TABLE METHOD (
	ID BIGSERIAL PRIMARY KEY,
	INFO VARCHAR(1024)
);

CREATE TABLE TIME (
	ID BIGSERIAL PRIMARY KEY,
	SHIFT VARCHAR(3),
	DAY INT,
	MONTH INT,
	YEAR INT,
	
	MONTH_CHAR VARCHAR(32),
	DAY_OF_WEEK INT,
	DAY_OF_WEEK_CHAR VARCHAR(14)
);


CREATE TABLE OFFENSE (
	ID BIGSERIAL PRIMARY KEY,
	INFO VARCHAR(1024)
);

CREATE TABLE DISTRICT (
	ID BIGSERIAL PRIMARY KEY,
	INFO VARCHAR(7)
);

CREATE TABLE SITE (
	ID BIGSERIAL PRIMARY KEY,
	ADDRESS VARCHAR(1024),
	CLUSTER INT,
	REGION VARCHAR(3),
	PSA INT,
	WARD INT
);

CREATE TABLE FACT (
	CCN BIGINT,
	M_ID BIGINT REFERENCES METHOD(ID),
	O_ID BIGINT REFERENCES OFFENSE(ID),
	S_ID BIGINT REFERENCES SITE(ID),
	T_ID BIGINT REFERENCES TIME(ID),
	D_ID BIGINT REFERENCES DISTRICT(ID),
	
	PRIMARY KEY ( CCN,
		M_ID, O_ID, S_ID, T_ID,
		D_ID)
);